export const classes = [
  { quarter: "Spr '26", title: 'CSE 101M', name: 'Math Thinking for CS', units: "5.00", link: "" },
  { quarter: "Spr '26", title: 'CSE 160', name: 'Intro Comp Graphics', units: "7.00", link: "" },
  { quarter: "Win '26", title: 'CSE 111', name: 'Adv Programming', units: "5.00", link: "" },
  { quarter: "Win '26", title: 'CSE 140', name: 'Artif Intelligence', units: "5.00", link: "" },
  { quarter: "Win '26", title: 'CSE 186', name: 'Full Stack Web Dev. I', units: "5.00", link: "" },
  { quarter: "Fall '25", title: 'CSE 132', name: 'Computer Security', units: "5.00", link: "" },
  { quarter: "Fall '25", title: 'CSE 180', name: 'Database Systems I', units: "5.00", link: "" },
  { quarter: "Fall '25", title: 'CSE 186', name: 'Full Stack Web Dev. I', units: "5.00", link: "" },
  { quarter: "Sum '25", title: 'AM 30', name: 'SOE Calculus III', units: "5.00", link: "" },
  { quarter: "Sum '25", title: 'MUSC 58', name: 'Songwriting Craft', units: "5.00", link: "" },
  { quarter: "Spr '25", title: 'STAT 131', name: 'Intro Prob Theory', units: "5.00", link: "" },
  { quarter: "Spr '25", title: 'AM 10', name: 'Math Methods I', units: "5.00", link: "" },
  { quarter: "Spr '25", title: 'ECE 30', name: 'Engr Prin of Elec', units: "5.00", link: "" },
  { quarter: "Win '25", title: 'CSE 102', name: 'Intro Algorithm Anyl.', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse102" },
  { quarter: "Win '25", title: 'CSE 115a', name: 'Intro Software Eng.', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse115a" },
  { quarter: "Win '25", title: 'CSE 120', name: 'Computer Architecture', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse120" },
  { quarter: "Fall '24", title: 'CSE 40', name: 'ML Basics', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse40" },
  { quarter: "Fall '24", title: 'CSE 114A', name: 'Found of Program Lang', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse114A" },
  { quarter: "Fall '24", title: 'CSE 130', name: 'Prin Comp Sys Dsgn', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse130" },
  { quarter: "Spr '24", title: 'CSE 101', name: 'Data Structs & Algs', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse101" },
  { quarter: "Spr '24", title: 'LING 80K', name: 'Invented Languages', units: "5.00", link: "https://catalog.ucsc.edu/en/current/general-catalog/courses/ling-linguistics/lower-division/ling-80k/" },
  { quarter: "Win '24", title: 'CMPM 80K', name: 'FoundationsGameDesgn', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cmpm80K" },
  { quarter: "Win '24", title: 'CSE 16', name: 'Appl Discrete Math', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse16" },
  { quarter: "Win '24", title: 'CSE 80N', name: 'Intro to Networking', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse80N" },
  { quarter: "Fall '23", title: 'CSE 13S', name: 'Comp Sys and C Prog', units: "7.00", link: "https://courses.engineering.ucsc.edu/courses/cse13S" },
  { quarter: "Fall '23", title: 'MATH 19B', name: 'Calc:Sci,Engin,Math', units: "5.00", link: "" },
  { quarter: "Fall '23", title: 'THEA 80U', name: 'Everybody Dance Now', units: "5.00", link: "" },
  { quarter: "Spr '23", title: 'CSE 12', name: 'Com Sys/Assmbly Lan', units: "7.00", link: "https://courses.engineering.ucsc.edu/courses/cse12" },
  { quarter: "Spr '23", title: 'LING 50', name: 'Intr To Linguistics', units: "5.00", link: "" },
  { quarter: "Spr '23", title: 'WRIT 2', name: 'Rhetoric & Inquiry', units: "5.00", link: "" },
  { quarter: "Win '23", title: 'CSE 30', name: 'Prog Abs Python', units: "7.00", link: "https://courses.engineering.ucsc.edu/courses/cse30" },
  { quarter: "Win '23", title: 'MATH 19A', name: 'Calc:Sci,Engin,Math', units: "5.00", link: "" },
  { quarter: "Win '23", title: 'TIM 50', name: 'Business Inf System', units: "5.00", link: "" },
  { quarter: "Fall '22", title: 'BME 5', name: 'Intro to Biotech', units: "5.00", link: "" },
  { quarter: "Fall '22", title: 'CRWN 1', name: 'ALE:Emerging Tech', units: "5.00", link: "" },
  { quarter: "Fall '22", title: 'CSE 20', name: 'Beginning Python', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse20" },
  { quarter: "Sum '22", title: 'CRWN 1A', name: 'Univ Life & Learning', units: "1.00", link: "" },
];