export const classes = [
  { quarter: "Win '25", title: 'CSE 102', name: 'Intro Algorithm Anyl.', grade: 'In progress', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse102" },
  { quarter: "Win '25", title: 'CSE 115a', name: 'Intro Software Eng.', grade: 'In progress', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse115a" },
  { quarter: "Win '25", title: 'CSE 120', name: 'Computer Architecture', grade: 'In progress', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse120" },
  { quarter: "Fall '24", title: 'CSE 40', name: 'ML Basics', grade: 'A-', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse40" },
  { quarter: "Fall '24", title: 'CSE 114A', name: 'Found of Program Lang', grade: 'B', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse114A" },
  { quarter: "Fall '24", title: 'CSE 130', name: 'Prin Comp Sys Dsgn', grade: 'B+', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse130" },
  { quarter: "Spr '24", title: 'CSE 101', name: 'Data Structs & Algs', grade: 'A', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse101" },
  { quarter: "Spr '24", title: 'LING 80K', name: 'Invented Languages', grade: 'B', units: "5.00", link: "https://catalog.ucsc.edu/en/current/general-catalog/courses/ling-linguistics/lower-division/ling-80k/" },
  { quarter: "Win '24", title: 'CMPM 80K', name: 'FoundationsGameDesgn', grade: 'A', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cmpm80K" },
  { quarter: "Win '24", title: 'CSE 16', name: 'Appl Discrete Math', grade: 'A', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse16" },
  { quarter: "Win '24", title: 'CSE 80N', name: 'Intro to Networking', grade: 'A+', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse80N" },
  { quarter: "Fall '23", title: 'CSE 13S', name: 'Comp Sys and C Prog', grade: 'A', units: "7.00", link: "https://courses.engineering.ucsc.edu/courses/cse13S" },
  { quarter: "Fall '23", title: 'MATH 19B', name: 'Calc:Sci,Engin,Math', grade: 'B+', units: "5.00", link: "" },
  { quarter: "Fall '23", title: 'THEA 80U', name: 'Everybody Dance Now', grade: 'A', units: "5.00", link: "" },
  { quarter: "Spr '23", title: 'CSE 12', name: 'Com Sys/Assmbly Lan', grade: 'A', units: "7.00", link: "https://courses.engineering.ucsc.edu/courses/cse12" },
  { quarter: "Spr '23", title: 'LING 50', name: 'Intr To Linguistics', grade: 'B', units: "5.00", link: "" },
  { quarter: "Spr '23", title: 'WRIT 2', name: 'Rhetoric & Inquiry', grade: 'A', units: "5.00", link: "" },
  { quarter: "Win '23", title: 'CSE 30', name: 'Prog Abs Python', grade: 'B', units: "7.00", link: "https://courses.engineering.ucsc.edu/courses/cse30" },
  { quarter: "Win '23", title: 'MATH 19A', name: 'Calc:Sci,Engin,Math', grade: 'A', units: "5.00", link: "" },
  { quarter: "Win '23", title: 'TIM 50', name: 'Business Inf System', grade: 'A', units: "5.00", link: "" },
  { quarter: "Fall '22", title: 'BME 5', name: 'Intro to Biotech', grade: 'B', units: "5.00", link: "" },
  { quarter: "Fall '22", title: 'CRWN 1', name: 'ALE:Emerging Tech', grade: 'A', units: "5.00", link: "" },
  { quarter: "Fall '22", title: 'CSE 20', name: 'Beginning Python', grade: 'A', units: "5.00", link: "https://courses.engineering.ucsc.edu/courses/cse20" },
  { quarter: "Sum '22", title: 'CRWN 1A', name: 'Univ Life & Learning', grade: 'P', units: "1.00", link: "" },
];